apiVersion: v1
kind: Service
metadata:
  name: items-api
  labels:
    app: items-api
spec:
  selector:
    app: items-api
  ports:
    - name: http
      port: 80
      targetPort: 8888
  type: ClusterIP
